// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSyncAPI.Data;

#nullable disable

namespace SkillSyncAPI.Migrations
{
    [DbContext(typeof(SkillSyncDbContext))]
    [Migration("20251130121838_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillSyncAPI.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Building a modern e-commerce platform with .NET Core backend and React frontend. Features include user authentication, product catalog, shopping cart, and payment integration.",
                            Name = "E-Commerce Platform",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CRM system to manage customer relationships, track sales, and generate reports. Built with ASP.NET Core Web API and Angular frontend.",
                            Name = "Customer Management System",
                            Status = "OnHold",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure mobile banking application with features like account management, fund transfers, bill payments, and transaction history.",
                            Name = "Mobile Banking App",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.ProjectAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("RoleOnProject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_on_project");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("project_assignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            AssignedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("40000000-0000-0000-0000-000000000001"),
                            RoleOnProject = "Senior Backend Developer",
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AssignedAt = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("40000000-0000-0000-0000-000000000001"),
                            RoleOnProject = "Full Stack Developer",
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            AssignedAt = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("40000000-0000-0000-0000-000000000002"),
                            RoleOnProject = "Frontend Developer",
                            Status = "Inactive",
                            UserId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            AssignedAt = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedAt = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("40000000-0000-0000-0000-000000000003"),
                            RoleOnProject = "Tech Lead",
                            Status = "Completed",
                            UserId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            AssignedAt = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedAt = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("40000000-0000-0000-0000-000000000003"),
                            RoleOnProject = "DevOps Engineer",
                            Status = "Completed",
                            UserId = new Guid("30000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Talent"
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = "Backend Development",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = "Backend Development",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = "Backend Development",
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Category = "Backend Development",
                            Name = "RESTful API"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Category = "Frontend Development",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Category = "Frontend Development",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Category = "Frontend Development",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Category = "Frontend Development",
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Category = "Database",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Category = "Database",
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Category = "DevOps",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Category = "DevOps",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Category = "DevOps",
                            Name = "CI/CD"
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.TalentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("availability_status");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId");

                    b.ToTable("talent_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            AvailabilityStatus = "Available",
                            Bio = "Senior .NET developer with 5+ years of experience in building scalable web applications. Expertise in ASP.NET Core, Entity Framework, and cloud technologies.",
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            FirstName = "John",
                            LastName = "Doe",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            AvailabilityStatus = "Available",
                            Bio = "Full-stack developer specializing in React and .NET technologies. Strong background in database design and API development.",
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            FirstName = "Jane",
                            LastName = "Smith",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            AvailabilityStatus = "OnLeave",
                            Bio = "DevOps engineer with expertise in containerization, CI/CD pipelines, and cloud infrastructure management.",
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "DevOps",
                            FirstName = "Mike",
                            LastName = "Wilson",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.TalentSkill", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("skill_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("talent_skills", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Level = "Expert"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Level = "Intermediate"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Level = "Expert"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000012"),
                            Level = "Expert"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000013"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000014"),
                            Level = "Advanced"
                        },
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Level = "Intermediate"
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$N2oKjyGJN5e5FbZ3vHkdLO1KJxCvYuZx3pRqF8tVwYsOZx9HkQ.mG",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$M1nJiyFIN4d4EaY2uGjcKN0JIwBuXtYw2oQpE7sUvXrNYx8GjP.lF",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "hr.manager"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.pm@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$L0mHhxEHM3c3DaX1tFibJM9IHvAtWsXv1nPoD6rTuWqMXw7FiO.kE",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "pm.john"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$K9lGgwDGL2b2CaW0sFhaIM8HGuAsVrWu0mOnC5qSsVpLWv6EhN.jD",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$J8kFfvCFK1a1BaV9rEgaHL7GFtArUqVt9lNmB4pRrUoKVu5DgM.iC",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "jane.smith"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mike.wilson@skillsync.com",
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$11$I7jEeuBEJ0Z0AaU8qDfaGK6FEsAqTpUs8kMlA3oQqTnJTt4CfL.hB",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "mike.wilson"
                        });
                });

            modelBuilder.Entity("SkillSyncAPI.Models.ProjectAssignment", b =>
                {
                    b.HasOne("SkillSyncAPI.Models.Project", "Project")
                        .WithMany("ProjectAssignment")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSyncAPI.Models.User", "User")
                        .WithMany("ProjectAssignment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.TalentProfile", b =>
                {
                    b.HasOne("SkillSyncAPI.Models.User", "User")
                        .WithOne("TalentProfile")
                        .HasForeignKey("SkillSyncAPI.Models.TalentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.TalentSkill", b =>
                {
                    b.HasOne("SkillSyncAPI.Models.Skill", "Skill")
                        .WithMany("TalentSkill")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSyncAPI.Models.TalentProfile", "TalentProfile")
                        .WithMany("TalentSkill")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("TalentProfile");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.User", b =>
                {
                    b.HasOne("SkillSyncAPI.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.Project", b =>
                {
                    b.Navigation("ProjectAssignment");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.Skill", b =>
                {
                    b.Navigation("TalentSkill");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.TalentProfile", b =>
                {
                    b.Navigation("TalentSkill");
                });

            modelBuilder.Entity("SkillSyncAPI.Models.User", b =>
                {
                    b.Navigation("ProjectAssignment");

                    b.Navigation("TalentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
